#!/bin/bash

# Commands to run in Droplet Console to get environment variables
# Copy and paste these commands into your DigitalOcean Droplet console

echo "=== Commands to run in Droplet Console ==="
echo ""
echo "1. Check current directory and app location:"
echo "   pwd"
echo "   ls -la"
echo ""
echo "2. Find the application directory:"
echo "   find /var/www -name 'ecosystem.config.js' 2>/dev/null"
echo "   find /home -name 'ecosystem.config.js' 2>/dev/null | head -5"
echo ""
echo "3. Get environment variables from PM2 ecosystem.config.js:"
echo "   cd /var/www/trendyfashions  # or wherever your app is"
echo "   cat ecosystem.config.js | grep -A 30 'env:' | grep -E '^\s+[A-Z_]+:'"
echo ""
echo "4. Get environment variables from .env file:"
echo "   cat .env 2>/dev/null || cat .env.local 2>/dev/null || cat .env.production 2>/dev/null"
echo ""
echo "5. Get environment variables from PM2 process:"
echo "   pm2 env 0 2>/dev/null"
echo "   pm2 show trendy-fashion-zone 2>/dev/null | grep -A 100 'env:'"
echo ""
echo "6. Get all environment variables (combine all sources):"
echo "   echo '=== From ecosystem.config.js ==='"
echo "   cat ecosystem.config.js | grep -A 30 'env:' | grep -E '^\s+[A-Z_]+:' | sed 's/^\s*//;s/://;s/,$//' | sed \"s/'//g\""
echo "   echo ''"
echo "   echo '=== From .env file ==='"
echo "   cat .env 2>/dev/null || cat .env.local 2>/dev/null || echo 'No .env file found'"
echo "   echo ''"
echo "   echo '=== From PM2 process ==='"
echo "   pm2 env 0 2>/dev/null | grep -E '^[A-Z_]+=' || echo 'PM2 env not available'"
echo ""
echo "7. Save all environment variables to a file:"
echo "   {"
echo "     echo '# Environment Variables from Server'"
echo "     echo '# Generated on: $(date)'"
echo "     echo ''"
echo "     echo '# From ecosystem.config.js'"
echo "     cat ecosystem.config.js | grep -A 30 'env:' | grep -E '^\s+[A-Z_]+:' | sed 's/^\s*//;s/://;s/,$//' | sed \"s/'//g\" | sed 's/^/export /'"
echo "     echo ''"
echo "     echo '# From .env file'"
echo "     cat .env 2>/dev/null || cat .env.local 2>/dev/null || echo '# No .env file found'"
echo "   } > /tmp/server-env-vars.txt"
echo "   cat /tmp/server-env-vars.txt"
echo ""
